/* 
 * V2__createProductModel.sql
 * Erzeugt alle Datenbank-Objekte für das Product-Datenmodell.
 */

CREATE TABLE T_PRODUCT (
	PRODUCT_ID BIGINT PRIMARY KEY NOT NULL ,
    PRODUCT_NAME VARCHAR(255) NOT NULL ,
    BESCHREIBUNG VARCHAR(1500) NOT NULL ,
    GROESSE VARCHAR(32) ,
    PREIS DECIMAL(8,2) ,
    VERSION INT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFICATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX X_PRODUCT
ON T_PRODUCT
(PRODUCT_ID ASC);
   
INSERT INTO T_SEQUENCE VALUES ('T_PRODUCT', 1000);
