/* 
 * V2__createOrderModel.sql
 * Erzeugt alle Datenbank-Objekte für das Order-Datenmodell.
 */

CREATE TABLE T_ORDER (
	ORDER_ID BIGINT PRIMARY KEY NOT NULL ,
    STATUS INT NOT NULL,
    VERSION INT NOT NULL,
    SUBMISSION_DATE TIMESTAMP NOT NULL,
    COMPLETION_DATE TIMESTAMP NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFICATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX X_ORDER
ON T_ORDER
(ORDER_ID ASC);
   
INSERT INTO T_SEQUENCE VALUES ('T_PRODUCT', 1000);
